trigger:
- none

variables:
  policiesDirectory: "$(System.DefaultWorkingDirectory)/policies/"
  assignmentsDirectory: "$(System.DefaultWorkingDirectory)/assignments/subscriptions/"
  serviceConnection: 'SP'
  subscriptionId: '64681aa1-73cc-4155-aa97-caa0e4837412'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: 'DeployAzurePolicy'
  displayName: 'Deploy Azure Policy'
  jobs:
  - job: 'DeployPolicy'
    displayName: 'Deploy Policy'
    steps:
    - checkout: self
      clean: true

    - task: AzureCLI@2
      inputs:
        azureSubscription: '$(serviceConnection)'
        scriptType: 'bash'
        scriptLocation: 'scriptPath'
        scriptPath: 'pipeline-scripts/deploy-policies.sh'
        arguments: '$(subscriptionId) $(policiesDirectory) $(assignmentsDirectory)/$(subscriptionId)'

    - task: AzureCLI@2
      inputs:
        azureSubscription: '$(serviceConnection)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az policy state trigger-scan --resource '/subscriptions/$(subscriptionId)'