trigger:
- none

variables:
  policiesDirectory: "$(System.DefaultWorkingDirectory)/policies/"
  assignmentsDirectory: "$(System.DefaultWorkingDirectory)/assignments/subscriptions"
  serviceConnection: 'ServiceConnection'
  subscriptionId: '14a92e37-f24d-48ee-a857-6e2dcbbadc09'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: deploy_policies
  displayName: 'Deploy Azure Policies'
  jobs:
    - job: Deploy
      displayName: 'Deploy Policy Definitions and Assignments'
      steps:
        - checkout: self

        - task: AzureCLI@2
          displayName: 'Deploy Policy Definitions and Assignments'
          inputs:
            azureSubscription: '$(serviceConnection)'
            scriptType: 'bash'
            scriptLocation: 'scriptPath'
            scriptPath: 'pipeline-scripts/deploy-policies.sh'
            arguments: '$(subscriptionId) $(policiesDirectory) $(assignmentsDirectory)/$(subscriptionId)'

        - task: AzureCLI@2
          displayName: 'Trigger Compliance Scan'
          inputs:
            azureSubscription: '$(serviceConnection)'
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              resourceGroups=$(az group list --subscription $(subscriptionId) --query "[].name" -o tsv)
              for rg in $resourceGroups; do
                az policy state trigger-scan --resource-group $rg &
              done
              wait

- stage: deploy_security_devops
  displayName: 'Deploy Security DevOps'
  jobs:
    - job: DeploySecurity
      displayName: 'Microsoft Security DevOps'
      steps:
        - checkout: self

        - script: cd src
          displayName: 'Change to src directory'

        - task: AdvancedSecurity-Codeql-Init@1
          inputs:
            languages: 'javascript'

        - task: AdvancedSecurity-Codeql-Autobuild@1
          displayName: 'Advanced Security Autobuild' 

        - task: AdvancedSecurity-Dependency-Scanning@1
          displayName: 'Dependency Scanning'

        - task: AdvancedSecurity-Codeql-Analyze@1
          displayName: 'Perform CodeQL Analysis'
          inputs:
            languages: 'javascript'

        - task: AdvancedSecurity-Publish@1
          displayName: 'Publish Security Results'

        - task: MicrosoftSecurityDevOps@1
          displayName: 'Microsoft Security DevOps'