trigger:
- none

variables:
  policiesDirectory: "$(System.DefaultWorkingDirectory)/policies/"
  assignmentsDirectory: "$(System.DefaultWorkingDirectory)/assignments/subscriptions/"
  serviceConnection: 'SP'
  subscriptionId: '64681aa1-73cc-4155-aa97-caa0e4837412'

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: DeployPolicies
    displayName: 'Deploy Azure Policies'
    jobs:
      - job: Deploy
        displayName: 'Deploy Policy Definitions and Assignments'
        steps:
          - checkout: self

          - task: AzureCLI@2
            displayName: 'Deploy Policy Definitions'
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                for policy in $(find $(policiesDirectory) -name policy.json); do
                  echo "Deploying policy: $policy"
                  az policy definition create --name $(basename $(dirname $policy)) --policy @$policy --mode All
                done

          - task: AzureCLI@2
            displayName: 'Deploy Policy Assignments'
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                for assignment in $(find $(assignmentsDirectory) -name 'assign.*.json'); do
                  echo "Deploying assignment: $assignment"
                  az policy assignment create --name $(basename $assignment .json) --policy @$assignment --scope /subscriptions/$(subscriptionId)
                done
