name: manage-azure-policy

on:
  push:
    branches: [master]
  pull_request:

jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    - name: Create or Update Azure Policies
      run: |
        terraform init
        terraform apply -auto-approve
      env:
        AZURE_CREDENTIALS: ${{secrets.AZURE_CREDENTIALS}}

    - name: Evaluate Azure Policy Compliance
      run: |
        az policy assignment list --query "[?policyDefinitionId=='/providers/Microsoft.Authorization/policySetDefinitions/enable-monitoring-defender-cloud']"
      env:
        AZURE_CREDENTIALS: ${{secrets.AZURE_CREDENTIALS}}

    - name: Deploy Resources
      run: |
        az deployment group create --resource-group myResourceGroup --template-file azuredeploy.json
      env:
        AZURE_CREDENTIALS: ${{secrets.AZURE_CREDENTIALS}}

    - name: Check Compliance
      run: |
        compliance=$(az policy state list --query "[?complianceState=='NonCompliant']")
        if [ -n "$compliance" ]; then
          echo "Non-compliant resources found. Halting deployment."
          exit 1
        fi
      env:
        AZURE_CREDENTIALS: ${{secrets.AZURE_CREDENTIALS}}